---
all:
  children:
    nginx:
      hosts:
        nginx01.example.com:
        nginx02.example.com:
      vars:
        cert_service_type: nginx
    tomcat:
      hosts:
        tomcat01.example.com:
        tomcat02.example.com:
      vars:
        cert_service_type: tomcat
